const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const Routes = require('./Routes/Routes')
const cors = require('cors')
app.use(cors())
app.use(bodyParser.json())
app.use('/api/v2',Routes)
app.listen(4000,()=>{
    console.log('connected to port 4000 and localhost')
})